# Scrape data for Japanese Translation Activity project

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests
import re
from tqdm import tqdm
from ast import literal_eval # convert string list back to list from csv

In [2]:
BASE_URL = "https://bunpro.jp"
GRAMMAR_POINTS_URL = "https://bunpro.jp/grammar_points"
headers = {}

In [3]:
grammar_points_page = requests.get(GRAMMAR_POINTS_URL)

soup = BeautifulSoup(grammar_points_page.text, 'html.parser')

grammar_points_list = []

for child in soup.find_all(attrs={"class":"u-position_absolute u-inset_0"}, recursive=True):
    grammar_points_list.append(child.attrs["href"])

In [11]:
def extract_text(ex: str, example=False, en=False):
    ###
    # RETURNS: a 2d-array containing all sentence segments - in the format [[kanji, furigana, hira, grammar_char], [kanji, furigana, hira, grammar_char], ...]
    #          either kanji and furigana are None when the segment is hira text, and hira is None when the segment is a kanji word with furigana

    text = []
    tag_starts = [m.start() for m in re.finditer('<', ex)]
    tag_closes = [m.start() for m in re.finditer('>', ex)]
    word = ''
    furigana = ''
    hira = ''
    find_text = False

    for i in range(len(tag_starts)-1):
        current_text = [None, None, None, None]
        current_tag = ex[tag_starts[i]+1:tag_closes[i]]

        if example: # get the start and end indeces of grammar point characters in current example
            if 'text-primary-accent' in current_tag:
                find_text = True # look for next text to assign as a grammar character
            if '/span' in current_tag and find_text: # if the grammar character styling tag has finished, stop assigning text as grammar character
                find_text = False

        if current_tag == 'ruby': # upcoming word has furigana attached
            word = ex[tag_closes[i]+1:tag_starts[i+1]]
        elif current_tag == 'rt':
            furigana = ex[tag_closes[i]+1:tag_starts[i+1]]
            current_text[0] = word # append the kanji and furigana after furigana appears
            current_text[1] = furigana
            if find_text:
                current_text[3] = True

            word = '' # reset these for new kanji word and furigana
            furigana = ''
        else:
            # if en:
            #     if current_tag == 'strong':
            #         hira = ex[tag_closes[i]+1:tag_starts[i+1]]
            #         find_text = True
            if not current_tag == 'rp': # rp is a tag that is only used around parentheses so do not need it
                hira = ex[tag_closes[i]+1:tag_starts[i+1]] # regular hiragana text appears

                if not hira == '' and not hira == '\n': # all tags produce some text, even if it is empty, so filter it out
                    current_text[2] = hira.replace("'", "@@")
                    if find_text:
                        current_text[3] = True



        if not all(x is None for x in current_text):
            text.append(current_text) 
          
    return text

In [ ]:
print(grammar_points_list)

grammar_data_df = pd.DataFrame(columns=["level", "grammar_point_jp", "meaning_en", "description", "url"])

In [15]:
for url in tqdm(grammar_points_list):
    
    full_url = BASE_URL + url
    # full_url = "https://bunpro.jp/grammar_points/%E3%82%92"
# full_url = "https://bunpro.jp/grammar_points/%E8%81%9E%E3%81%93%E3%81%88%E3%82%8B"
    page_data = requests.get(full_url)

    soup = BeautifulSoup(page_data.text, "html.parser")

    level = soup.find("p", {"class": "text-primary-contrast md:text-primary-fg"})
    level = str(level.text)[1:2]

    grammar_point_jp = soup.find("span", {"class": "bp-ddw undefined"})
    grammar_point_jp = extract_text(str(grammar_point_jp))

    meaning_en = soup.find("span", {"class": "mt-4 block text-body text-primary-contrast md:text-subtitle md:text-primary-fg"})
    meaning_en = meaning_en.text

    description = soup.find("div", {"class": "bp-ddw bp-writeup-body prose"})
    description = extract_text(str(description))

    grammar_data = {"level": level, "grammar_point_jp": grammar_point_jp, "meaning_en": meaning_en, "description": description, "url": full_url}

    grammar_data_df.loc[len(grammar_data_df)] = grammar_data

    # print(grammar_data)

100%|██████████| 938/938 [08:36<00:00,  1.82it/s]

In [ ]:
grammar_data_df["level"].loc[grammar_data_df['level'] == "o"] = 6
grammar_data_df = grammar_data_df.reset_index()
grammar_data_df.to_csv('grammar_points.csv', encoding='utf-8', header=False, index=True, columns=["level", "grammar_point_jp", "meaning_en", "description", "url"])
grammar_data_df

C:\Users\mcurt\AppData\Local\Temp\ipykernel_17872\1496420599.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grammar_data_df["level"].loc[grammar_data_df['level'] == "o"] = 6

,index,level,grammar_point_jp,meaning_en,description,url
0,938,5,"[[None, None, だ, None]]","To be, Is","[[None, None, For the most part, , None], [Non...",https://bunpro.jp/grammar_points/%E3%81%A0
1,939,5,"[[None, None, です, None]]","To be, Is","[[None, None, Similarly to , None], [None, Non...",https://bunpro.jp/grammar_points/%E3%81%A7%E3%...
2,940,5,"[[None, None, は, None]]",As for... (Highlights sentence topic),"[[None, None, は, None], [None, None, (pronoun...",https://bunpro.jp/grammar_points/%E3%81%AF
3,941,5,"[[None, None, も, None]]","Also, Too, As well, Even, Either, Neither","[[None, None, も, None], [None, None, can mean...",https://bunpro.jp/grammar_points/%E3%82%82
4,942,5,"[[None, None, これ, None]]",This,"[[None, None, これ, None], [None, None, is ofte...",https://bunpro.jp/grammar_points/%E3%81%93%E3%...
...,...,...,...,...,...,...
933,1871,6,"[[None, None, かろう, None]]","Probably, Right?","[[None, None, かろう is an old-fashioned grammar ...",https://bunpro.jp/grammar_points/%E3%81%8B%E3%...
934,1872,6,"[[None, None, やや, None]]","A little bit, Marginally, Slightly","[[None, None, やや is an adverb in Japanese that...",https://bunpro.jp/grammar_points/%E3%82%84%E3%...
935,1873,6,"[[None, None, いずれも, None]]","All (positive), None (negative), Both, Whateve...","[[None, None, いずれ is a formal adverb commonly ...",https://bunpro.jp/grammar_points/%E3%81%84%E3%...
936,1874,6,"[[None, None, あわよくば, None]]","If luck is on my side, If the time is right, I...","[[None, None, あわよくば is a combination of the ol...",https://bunpro.jp/grammar_points/%E3%81%82%E3%...
937,1875,6,"[[None, None, むず, None]]","Shall, Isn't it?, I wonder","[[None, None, むず is a combination and abbrevia...",https://bunpro.jp/grammar_points/%E3%82%80%E3%...

In [38]:
def get_grammar_char_locs(text: list):
    locs = []
    char_index = 0
    scan = False
    for i in range(len(text)):
        if text[i][3] is not None:
            if not scan:
                scan = True
                current_loc = []
                current_loc.append(char_index)
        else:
            if scan:
                scan = False
                current_loc.append(char_index)
                locs.append(current_loc)

        if text[i][0] is not None:
            char_index += len(text[i][0])
        else:
            char_index += len(text[i][2])
    if len(current_loc) == 1: # in case text ends with the grammar characters, add the end index manually
        current_loc.append(char_index)
        locs.append(current_loc)    
    
    return locs

### Read in data CSVs

In [39]:

# Read in grammar point dataframe

df = pd.read_csv('grammar_points.csv', encoding='utf-8', index_col=0, names=["level", "grammar_point_jp", "meaning_en", "description", "page_url"])

### Get examples from grammar points

In [41]:

# Create examples dataframe

examples_df = pd.DataFrame(columns=["grammar_id", "text_jp", "text_en", "grammar_char_locations_jp"])

# Get examples for each grammar point

for rec in tqdm(range(len(df))):
    url = df.loc[rec]['page_url']
    grammar_id = df.index[rec]

    page_data = requests.get(url)

    soup = BeautifulSoup(page_data.text, "html.parser")
    
    # Get example html of Japanese
    examples = soup.find_all("p", {"class": "bp-ddw prose text-large md:text-subtitle"})
    num_examples = len(examples)

    # Get example html of English
    examples_en = soup.find_all("p", {"class": "bp-sdw text-body prose"})

    for ex in range(num_examples):
        text_jp = extract_text(str(examples[ex]), example=True)
        grammar_char_locations_jp = get_grammar_char_locs(text_jp)

        text_en = examples_en[ex].text

        data = {"grammar_id": grammar_id, "text_jp": text_jp, "text_en": text_en, "grammar_char_locations_jp": grammar_char_locations_jp}
        examples_df.loc[len(examples_df)] = data

examples_df.to_csv('examples.csv', encoding='utf-8', header=False)

100%|██████████| 938/938 [07:36<00:00,  2.06it/s]

In [42]:
examples_df

,grammar_id,text_jp,text_en,grammar_char_locations_jp
0,0,"[[私, わたし, None, None], [None, None, だ, True], ...",It is me.,"[[1, 2]]"
1,0,"[[本, ほん, None, None], [None, None, だ, True], [...",It is a book.,"[[1, 2]]"
2,0,"[[猫, ねこ, None, None], [None, None, だ, True], [...",(It) is a cat.,"[[1, 2]]"
3,0,"[[学生, がくせい, None, None], [None, None, だ, True]...",(I) am a student.,"[[2, 3]]"
4,0,"[[綺麗, きれい, None, None], [None, None, だ, True],...",It is beautiful.,"[[2, 3]]"
...,...,...,...,...
4684,937,"[[世, よ, None, None], [None, None, の, None], [流...","Without defying the tide of the times, I shall...","[[13, 19]]"
4685,937,"[[None, None, いかに, None], [世, よ, None, None], ...",No matter how much I know the transience of th...,"[[26, 32]]"
4686,937,"[[花, はな, None, None], [None, None, の, None], [...",That which was enticed by the scent of flowers...,"[[13, 17]]"
4687,937,"[[None, None, この, None], [花, はな, None, None], ...",I shall deliver these flowers to my mother.,"[[6, 10]]"
4688,937,"[[道険, みちけわ, None, None], [None, None, しくとも、, N...","Even if the way is treacherous, I shall go on ...","[[13, 19]]"

In [43]:
examples_df.to_csv('examples.csv', encoding='utf-8', header=False, index=True)