# Scrape data for Japanese Translation Activity project

In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import requests
import re
from tqdm import tqdm
from ast import literal_eval # convert string list back to list from csv

In [3]:
BASE_URL = "https://bunpro.jp"
GRAMMAR_POINTS_URL = "https://bunpro.jp/grammar_points"
headers = {}

In [9]:
grammar_points_page = requests.get(GRAMMAR_POINTS_URL)

soup = BeautifulSoup(grammar_points_page.text, 'html.parser')

grammar_points_list = []

for child in soup.find_all(attrs={"class":"u-position_absolute u-inset_0"}, recursive=True):
    grammar_points_list.append(child.attrs["href"])

In [10]:
print(grammar_points_list)

grammar_data_df = pd.DataFrame(columns=["level", "grammar_point_jp", "meaning_en", "description"])


# "text" field format: [["word", "furigana"], ["word", "furigana"], ...]
# "grammar_char_location": indeces where the grammar point appears in the text, for later highlighting

['/grammar_points/%E3%81%A0', '/grammar_points/%E3%81%A7%E3%81%99', '/grammar_points/%E3%81%AF', '/grammar_points/%E3%82%82', '/grammar_points/%E3%81%93%E3%82%8C', '/grammar_points/%E3%81%9D%E3%82%8C', '/grammar_points/%E3%81%82%E3%82%8C', '/grammar_points/%E3%81%AE', '/grammar_points/%E3%81%84%E3%81%84', '/grammar_points/%E3%81%84-adjectives', '/grammar_points/%E3%81%AA-adjectives', '/grammar_points/%E3%81%8B', '/grammar_points/%E3%81%8C', '/grammar_points/%E3%82%88', '/grammar_points/%E3%81%AD', '/grammar_points/%E3%82%8B-Verbs', '/grammar_points/%E3%81%86-Verbs', '/grammar_points/%E3%82%92', '/grammar_points/polite-verb-endings', '/grammar_points/%E3%82%8Bverb-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%86verb--%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A8-and', '/grammar_points/%E3%81%93%E3%81%93', '/grammar_points/%E3%81%9D%E3%81%93', '/grammar_points/%E3%81%82%E3%81%9D%E3%81%93', '/grammar_points/%E3%81%A7', '/grammar_points/%E3%81%AB', '/grammar_points/%E3%81%8B-or', '/grammar_points/%E3%81%A8-with', '/grammar_points/%E3%81%A7%E3%81%97%E3%82%87%E3%81%86', '/grammar_points/%E3%81%A0%E3%82%8D%E3%81%86', '/grammar_points/%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%8C%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%AE', '/grammar_points/%E3%81%9D%E3%81%AE', '/grammar_points/%E3%81%82%E3%81%AE', '/grammar_points/-%E3%82%93%E3%81%A7%E3%81%99-%E3%81%AE%E3%81%A7%E3%81%99', '/grammar_points/past-tense-%E3%81%84-adjectives', '/grammar_points/%E3%81%AE%E3%81%AF', '/grammar_points/%E3%81%84-adjective-noun', '/grammar_points/%E3%81%AA-adjective-noun', '/grammar_points/%E3%81%B8%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%8F%E3%82%8B', '/grammar_points/%E3%82%8B-verb-past', '/grammar_points/%E3%81%86-verb-past', '/grammar_points/%E3%81%99%E3%81%8D', '/grammar_points/%E3%81%8D%E3%82%89%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%99%E3%81%8D', '/grammar_points/%E3%81%8C%E3%81%82%E3%82%8B-noun', '/grammar_points/negative-%E3%81%84-adjectives', '/grammar_points/%E3%81%A7-by', '/grammar_points/%E3%81%AE%E3%81%A7', '/grammar_points/%E3%81%8B%E3%82%89-because', '/grammar_points/%E3%81%8B%E3%82%89', '/grammar_points/%E3%81%91%E3%81%A9-%E3%81%A0%E3%81%91%E3%81%A9', '/grammar_points/%E3%81%8C-but', '/grammar_points/%E3%82%8B-verb-neg-past', '/grammar_points/%E3%81%86-verb-neg-past', '/grammar_points/verb-%E3%81%A6', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B1', '/grammar_points/%E3%81%B8', '/grammar_points/verb-%E3%81%AB%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%A0%E3%82%8C', '/grammar_points/%E3%81%84-adjective-predicate', '/grammar_points/%E3%81%AA-adjective-predicate', '/grammar_points/%E3%81%A0%E3%81%A3%E3%81%9F-%E3%81%A7%E3%81%97%E3%81%9F', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%84-Adjective-%E3%81%8F%E3%81%AA%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%A8', '/grammar_points/%E3%81%A3%E3%81%A6', '/grammar_points/verb-non-past', '/grammar_points/verb-%E3%81%9F-noun', '/grammar_points/%E3%81%AE-noun-ommission', '/grammar_points/%E3%81%AA', '/grammar_points/%E3%81%A0%E3%81%91', '/grammar_points/%E3%81%A9%E3%82%8C', '/grammar_points/%E3%81%A9%E3%81%93', '/grammar_points/%E3%81%A9%E3%81%AE', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B2', '/grammar_points/%E3%81%A6%E3%81%8B%E3%82%89', '/grammar_points/verb-%E3%81%A6-b', '/grammar_points/%E3%82%82%E3%81%86', '/grammar_points/%E3%81%BE%E3%81%A0', '/grammar_points/%E3%81%BE%E3%81%A0-%E3%81%A6%E3%81%84%E3%81%BE%E3%81%9B%E3%82%93', '/grammar_points/%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%9F%E3%82%8A-%E3%81%9F%E3%82%8A%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%91%E3%81%A3%E3%81%93%E3%81%86', '/grammar_points/%E3%81%9F%E3%81%8F%E3%81%95%E3%82%93', '/grammar_points/%E3%81%BE%E3%81%88%E3%81%AB', '/grammar_points/%E3%81%8F%E3%82%89%E3%81%841', '/grammar_points/noun-%E3%81%BE%E3%81%A7', '/grammar_points/v-%E3%81%BE%E3%81%A7', '/grammar_points/%E3%81%99%E3%81%8E%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%AA%E3%82%8B-%E3%81%8F%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AE%E3%81%AA%E3%81%8B%E3%81%A7-%E3%81%8C%E3%81%84%E3%81%A1%E3%81%B0%E3%82%93', '/grammar_points/%E3%82%88%E3%82%8A-%E3%81%AE%E3%81%BB%E3%81%86%E3%81%8C', '/grammar_points/%E3%81%AA%E3%81%AB%E3%81%8B-%E3%81%AA%E3%81%AB%E3%82%82', '/grammar_points/%E8%AA%B0%E3%81%8B-%E3%81%A9%E3%81%93%E3%81%8B-%E8%AA%B0%E3%82%82-%E3%81%A9%E3%81%93%E3%82%82', '/grammar_points/%E3%81%BE%E3%81%97%E3%82%87%E3%81%86', '/grammar_points/%E3%81%BE%E3%81%97%E3%82%87%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%BE%E3%81%9B%E3%82%93%E3%81%8B', '/grammar_points/verb-%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A7%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%9F%E3%81%BB%E3%81%86%E3%81%8C%E3%81%84%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%BB%E3%81%86%E3%81%8C%E3%81%84%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A1%E3%82%83-%E3%81%AA%E3%81%8D%E3%82%83', '/grammar_points/%E3%82%84', '/grammar_points/%E3%81%9F%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B3', '/grammar_points/adjective-%E3%81%A6-noun-%E3%81%A7', '/grammar_points/adjective-%E3%81%A6-b', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%B8%E3%81%9F', '/grammar_points/%E3%81%AE%E3%81%8C%E3%81%98%E3%82%87%E3%81%86%E3%81%9A', '/grammar_points/adjective-%E3%81%AE-%E3%81%AF', '/grammar_points/%E3%81%82%E3%81%92%E3%82%8B', '/grammar_points/%E3%81%8F%E3%82%8C%E3%82%8B', '/grammar_points/%E3%82%82%E3%82%89%E3%81%86', '/grammar_points/%E3%81%91%E3%82%8C%E3%81%A9%E3%82%82', '/grammar_points/%E3%81%A4%E3%82%82%E3%82%8A%E3%81%A0', '/grammar_points/%E3%81%A7%E3%82%82', '/grammar_points/%E3%82%84%E3%81%99%E3%81%84', '/grammar_points/%E3%81%AB%E3%81%8F%E3%81%84', '/grammar_points/%E3%81%A0%E3%82%93%E3%81%A0%E3%82%93', '/grammar_points/%E3%81%A9%E3%82%93%E3%81%A9%E3%82%93', '/grammar_points/%E3%82%89', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%8F', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8B', '/grammar_points/%E3%81%8B%E3%81%9F', '/grammar_points/%E3%81%A0%E3%81%91%E3%81%A7', '/grammar_points/%E3%81%A0%E3%81%8C%E3%83%BB%E3%81%A7%E3%81%99%E3%81%8C', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6-conjunction', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A7', '/grammar_points/Verb%5Bpassive%5D', '/grammar_points/transitive-intransitive-verbs', '/grammar_points/%E3%81%AA%E3%81%8A%E3%81%99', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8', '/grammar_points/%E3%81%A8%E3%81%8D', '/grammar_points/%E3%81%BE%E3%81%9A', '/grammar_points/%E3%81%BE%E3%81%A7', '/grammar_points/%E3%81%BE%E3%81%A7%E3%81%AB', '/grammar_points/%E3%81%BE%E3%81%9F', '/grammar_points/%E3%81%AF%E3%81%98%E3%82%81%E3%82%8B', '/grammar_points/%E3%81%8A%E3%82%8F%E3%82%8B', '/grammar_points/%E3%81%94%E3%82%8D', '/grammar_points/%E3%81%82%E3%81%A8%E3%81%A7', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%9F', '/grammar_points/%E3%81%AB-frequency', '/grammar_points/%E3%81%A8%E3%81%86%E3%81%A8%E3%81%86', '/grammar_points/%E3%82%88%E3%82%8A', '/grammar_points/%E3%81%94%E3%81%A8%E3%81%AB', '/grammar_points/%E3%81%AA%E3%82%8B%E3%81%B9%E3%81%8F', '/grammar_points/%E3%82%8B%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%AE%E3%81%AB-despite', '/grammar_points/%E3%81%A8%E3%81%8A%E3%82%82%E3%81%86', '/grammar_points/%E3%81%AA%E3%81%A9', '/grammar_points/%E3%81%BF%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%93%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%86', '/grammar_points/%E3%81%95', '/grammar_points/%E3%81%A8%E3%81%8B-%E3%81%A8%E3%81%8B', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%84%E3%81%86', '/grammar_points/%E3%82%88%E3%81%86-%E3%81%8A%E3%81%86', '/grammar_points/%E3%82%88%E3%81%86%E3%81%A0', '/grammar_points/%E3%81%9C%E3%82%93%E3%81%9C%E3%82%93', '/grammar_points/%E3%81%8B%E3%81%AA', '/grammar_points/%E3%81%82%E3%81%BE%E3%82%8A-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%B0', '/grammar_points/%E3%81%AA%E3%82%89', '/grammar_points/%E3%81%8C%E3%82%8B', '/grammar_points/%E3%81%8C%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%8C%E3%82%8B', '/grammar_points/%E3%81%8B%E3%82%82%E3%81%97%E3%82%8C%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AB-%E3%81%BF%E3%81%9F%E3%81%84%E3%81%AA', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%AB-%E3%81%9D%E3%81%86%E3%81%AA', '/grammar_points/%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB-%E3%81%AE%E3%82%88%E3%81%86%E3%81%AA', '/grammar_points/%E3%82%88%E3%81%86%E3%81%A8%E6%80%9D%E3%81%86-%E3%81%8A%E3%81%86%E3%81%A8%E6%80%9D%E3%81%86', '/grammar_points/describing-verbs', '/grammar_points/%E3%81%AB%E3%81%99%E3%82%8B-%E3%81%8F%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%84', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%BE%E3%81%84-%E3%81%AE%E3%82%88%E3%81%86%E3%81%AB', '/grammar_points/%E3%81%98%E3%82%83%E3%81%AA%E3%81%84%E3%81%8B', '/grammar_points/%E3%82%89%E3%81%97%E3%81%841', '/grammar_points/%E3%81%A6%E3%81%8A%E3%81%8F', '/grammar_points/%E3%81%8C%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A8%E3%81%8D%E3%81%84%E3%81%9F', '/grammar_points/%E8%81%9E%E3%81%93%E3%81%88%E3%82%8B', '/grammar_points/%E8%A6%8B%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A0%E3%81%99', '/grammar_points/%E4%BB%A3', '/grammar_points/number-%E3%82%82', '/grammar_points/%E3%81%BB%E3%81%A8%E3%82%93%E3%81%A9', '/grammar_points/%E3%81%9D%E3%82%93%E3%81%AA-%E3%81%93%E3%82%93%E3%81%AA-%E3%81%82%E3%82%93%E3%81%AA-%E3%81%A9%E3%82%93%E3%81%AA', '/grammar_points/%E5%90%84', '/grammar_points/%E4%BB%A5%E4%B8%8A1', '/grammar_points/%E3%81%84%E3%81%8B', '/grammar_points/%E3%81%84%E3%81%8C%E3%81%84', '/grammar_points/%E3%81%9A%E3%81%A3%E3%81%A81', '/grammar_points/%E3%81%A0%E3%81%84%E3%81%9F%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%AA%E3%81%8B%E3%81%A7', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB-%E3%82%88%E3%81%86%E3%81%AA', '/grammar_points/number-amount-%E3%81%AF', '/grammar_points/%E3%81%AA%E3%82%93-counter-%E3%81%8B', '/grammar_points/%E7%9C%9F(%E3%81%A3)', '/grammar_points/number-%E3%81%97%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AF-%E3%81%AE%E4%B8%80%E3%81%A4%E3%81%A0', '/grammar_points/%E3%81%AA%E3%81%84-%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%99%E3%81%93%E3%81%97%E3%82%82-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%99%E3%81%8F%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%B0%E3%81%82%E3%81%84%E3%81%AF', '/grammar_points/verb%E3%81%A6-request', '/grammar_points/%E3%81%A6%E3%82%88%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/causative', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%A3%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%82%82', '/grammar_points/%E3%81%A6%E3%81%97%E3%81%BE%E3%81%86-%E3%81%A1%E3%82%83%E3%81%86', '/grammar_points/verb%E3%81%A6-b2', '/grammar_points/causative-passive', '/grammar_points/verb-%E3%81%A6-noun-%E3%81%A7-b', '/grammar_points/%E3%81%A6%E3%81%82%E3%82%8B', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB-%E3%81%A6%E3%81%BB%E3%81%97%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B%E3%81%82%E3%81%84%E3%81%A0%E3%81%AB', '/grammar_points/%E3%81%AA%E3%81%8F%E3%81%A6%E3%82%82%E3%81%84%E3%81%84', '/grammar_points/%E3%81%A6%E3%81%BF%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%99%E3%81%BF%E3%81%BE%E3%81%9B%E3%82%93', '/grammar_points/%E3%81%A6%E3%81%82%E3%81%92%E3%82%8B', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%82%8B', '/grammar_points/%E3%81%A6%E3%82%82%E3%82%89%E3%81%86', '/grammar_points/%E3%81%AA%E3%81%95%E3%81%84', '/grammar_points/verb%E3%81%A6-b', '/grammar_points/verb-%E3%81%AA%E3%81%84%E3%81%A7', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%81%A6%E3%81%82%E3%82%8A%E3%81%8C%E3%81%A8%E3%81%86', '/grammar_points/%E3%81%A6%E3%81%8F%E3%82%8C%E3%81%AA%E3%81%84-%E3%81%A6%E3%82%82%E3%82%89%E3%81%88%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AE%E3%81%A0%E3%82%8D%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%8A-%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%95%E3%82%8B', '/grammar_points/%E3%81%8A-%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84', '/grammar_points/%E3%81%84%E3%82%89%E3%81%A3%E3%81%97%E3%82%83%E3%82%8B', '/grammar_points/%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99', '/grammar_points/%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99', '/grammar_points/%E3%81%8A-%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%84%E3%81%9F%E3%81%99', '/grammar_points/%E3%81%A6%E3%81%84%E3%81%9F%E3%81%A0%E3%81%91%E3%81%BE%E3%81%9B%E3%82%93%E3%81%8B', '/grammar_points/%E3%81%9F%E3%82%89', '/grammar_points/%E3%81%BB%E3%81%8B%E3%81%AB%E3%82%82-%E3%81%BB%E3%81%8B%E3%81%AB%E3%81%AF', '/grammar_points/%E3%81%8C%E3%81%B2%E3%81%A4%E3%82%88%E3%81%86', '/grammar_points/%E3%81%9D%E3%82%93%E3%81%AA%E3%81%AB', '/grammar_points/%E3%81%B2%E3%81%A4%E3%82%88%E3%81%86%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%A8%E3%81%88%E3%81%B0', '/grammar_points/Verb%5Bpotential%5D', '/grammar_points/%E3%82%93%E3%81%A0%E3%81%91%E3%81%A9-%E3%82%93%E3%81%A7%E3%81%99%E3%81%8C', '/grammar_points/%E3%81%AF%E3%81%9A%E3%81%A0', '/grammar_points/%E3%81%8B%E3%81%A9%E3%81%86%E3%81%8B', '/grammar_points/%E3%81%A8-conditional', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%A8', '/grammar_points/%E3%81%AF%E3%81%9A%E3%81%8C%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%97%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A0%E3%81%91%E3%81%A7%E3%81%AA%E3%81%8F', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B', '/grammar_points/%E3%81%8B%E3%81%84', '/grammar_points/%E3%82%82%E3%81%97', '/grammar_points/%E3%81%97-%E3%81%97', '/grammar_points/%E3%81%A7%E3%81%A7%E3%81%8D%E3%82%8B-%E3%81%8B%E3%82%89%E3%81%A7%E3%81%8D%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%8C%E3%82%89', '/grammar_points/%E3%81%9F%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%A6%E3%81%84%E3%82%8B%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A0', '/grammar_points/%E3%81%A8-%E3%81%A8-%E3%81%A9%E3%81%A1%E3%82%89%E3%81%8C', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%84%E3%81%91%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A4%E3%81%A5%E3%81%91%E3%82%8B', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%84%E3%81%86', '/grammar_points/%E3%82%88%E3%81%A6%E3%81%84%E3%81%A0', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB%E3%81%84%E3%81%AE%E3%82%8B', '/grammar_points/%E3%81%9F%E3%81%B0%E3%81%8B%E3%82%8A', '/grammar_points/%E5%8C%96%E3%81%99%E3%82%8B', '/grammar_points/%E5%91%BD%E4%BB%A4%E5%BD%A2', '/grammar_points/%E3%82%88%E3%81%86%E3%81%AB', '/grammar_points/%E3%81%8B%E3%81%97%E3%82%89', '/grammar_points/%E3%82%89%E3%81%97%E3%81%842', '/grammar_points/%E3%81%AB%E3%81%BF%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%BF%E3%81%88%E3%82%8B', '/grammar_points/%E9%A2%A8', '/grammar_points/%E3%81%8C%E3%81%BF%E3%82%89%E3%82%8C%E3%82%8B', '/grammar_points/%E3%81%AB%E3%81%8D%E3%81%8C%E3%81%A4%E3%81%8F', '/grammar_points/%E3%81%A7%E3%82%82-%E3%81%A7%E3%82%82', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%AB', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%A7', '/grammar_points/question-phrase-%E3%81%8B', '/grammar_points/%E3%81%9D%E3%82%8C%E3%81%A7%E3%82%82', '/grammar_points/%E3%81%9F%E3%82%89%E3%81%A9%E3%81%86', '/grammar_points/%E3%81%A8%E3%81%8B%E3%82%93%E3%81%8C%E3%81%88%E3%82%89%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%84%E3%82%8F%E3%82%8C%E3%81%A6%E3%81%84%E3%82%8B', '/grammar_points/%E3%81%B0%E3%82%88%E3%81%8B%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%B0%E3%81%84%E3%81%84', '/grammar_points/%E3%81%9F%E3%82%89%E3%81%84%E3%81%84-%E3%81%A8%E3%81%84%E3%81%84', '/grammar_points/%E4%B8%AD', '/grammar_points/%E3%81%AE%E9%96%93%E3%81%AB', '/grammar_points/%E3%81%86%E3%81%A1%E3%81%AB', '/grammar_points/%E3%81%AA%E3%81%84%E3%81%86%E3%81%A1%E3%81%AB', '/grammar_points/%E3%81%B9%E3%81%8D', '/grammar_points/%E3%81%B9%E3%81%8D%E3%81%A7%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A3%E3%81%A6-slang', '/grammar_points/%E3%81%AA%E3%81%8B%E3%81%AA%E3%81%8B', '/grammar_points/%E3%81%82%E3%81%BE%E3%82%8A', '/grammar_points/%E3%81%AA%E3%81%8B%E3%81%AA%E3%81%8B-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%AB%E3%82%88%E3%82%8B%E3%81%A8-%E3%81%AB%E3%82%88%E3%82%8C%E3%81%B0', '/grammar_points/%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6-%E3%81%AB%E3%82%88%E3%82%8B', '/grammar_points/%E5%85%A8%E3%81%8F-%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%A0', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%A0', '/grammar_points/%E3%81%99%E3%82%8B%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%86%E3%81%99%E3%82%8B%E3%81%A8', '/grammar_points/%E3%81%AE%E3%81%AFx%E3%81%AE%E6%96%B9%E3%81%A0', '/grammar_points/noun-%E5%9E%8B', '/grammar_points/%E3%81%A6%E3%81%94%E3%82%89%E3%82%93', '/grammar_points/particle-%E3%81%AE', '/grammar_points/%E3%81%A7%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%A8%E3%81%93%E3%82%8D%E3%81%8C', '/grammar_points/%E3%81%A8%E3%81%93%E3%82%8D%E3%81%A7', '/grammar_points/%E3%81%BB%E3%81%A9', '/grammar_points/%E3%81%B0-%E3%81%BB%E3%81%A9', '/grammar_points/%E3%81%BB%E3%81%A9%EF%BD%9E%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A7%E3%81%AF-%E3%81%9D%E3%82%8C%E3%81%A7%E3%81%AF-%E3%81%98%E3%82%83%E3%81%82', '/grammar_points/%E3%81%AE%E3%81%AB', '/grammar_points/%E3%81%9F%E3%82%81-%E3%81%AB', '/grammar_points/%E3%81%9F%E3%82%81%E3%81%AB', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86-called', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%93%E3%81%A8%E3%81%A0', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%86%E3%81%AE%E3%81%AF', '/grammar_points/%E7%9A%84', '/grammar_points/%E3%82%82%E3%81%AE-%E3%82%82%E3%82%93', '/grammar_points/%E3%82%82%E3%81%AE%E3%81%A0', '/grammar_points/%E6%9C%80%E4%B8%AD%E3%81%AB', '/grammar_points/%E4%B8%8A%E3%81%A7', '/grammar_points/%E3%81%8A%E3%81%8B%E3%81%92%E3%81%A7', '/grammar_points/%E3%81%AB%E3%82%82%E3%81%A8%E3%81%A5%E3%81%84%E3%81%A6', '/grammar_points/%E7%82%B9', '/grammar_points/%E3%81%AA%E3%81%9C%E3%81%AA%E3%82%89-%E3%81%8B%E3%82%89', '/grammar_points/%E3%81%93%E3%81%9D', '/grammar_points/%E3%81%8B%E3%82%89%E3%81%93%E3%81%9D', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A%E3%81%A0', '/grammar_points/%E3%81%B0%E3%81%8B%E3%82%8A%E3%81%AB', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%8C%E3%81%82%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AB%E3%81%99%E3%82%8B', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AA%E3%81%AE', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AB%E3%81%AA%E3%82%8B', '/grammar_points/%E3%81%AF-%E3%81%A7%E6%9C%89%E5%90%8D', '/grammar_points/%E3%81%93%E3%81%A8%E3%81%AF%E3%81%AA%E3%81%84', '/grammar_points/%E3%81%A8%E8%A8%80%E3%81%A3%E3%81%A6%E3%82%82', '/grammar_points/%E3%81%A8%E3%81%84%E3%81%88%E3%81%B0', '/grammar_points/%E5%90%88%E3%81%86', '/grammar_points/%E3%81%AB%E5%90%88%E3%82%8F%E3%81%9B%E3%81%A6-%E3%81%AB%E5%90%88%E3%81%A3%E3%81%9F', '/grammar_points/%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6', '/grammar_points/%E3%81%AE%E5%A7%BF', '/grammar_points/%E3%81%A8%E8%A8%80%E3%81%88%E3%82%8B', '/grammar_points/%E3%81%A1%E3%82%83%E3%82%93%E3%81%A8-%E3%81%8D%E3%81%A1%E3%82%93%E3%81%A8', '/grammar_points/%E3%81%9D%E3%81%AE%E3%81%9F%E3%82%81-%E3%81%AB', '/grammar_points/%E3%81%9D%E3%81%AE%E7%B5%90%E6%9E%9C', '/grammar_points/%E

In [ ]:
def extract_text(ex: str, example=False, en=False):
    ###
    # RETURNS: a 2d-array containing all sentence segments - in the format [[kanji, furigana, hira, grammar_char], [kanji, furigana, hira, grammar_char], ...]
    #          either kanji and furigana are None when the segment is hira text, and hira is None when the segment is a kanji word with furigana

    text = []
    tag_starts = [m.start() for m in re.finditer('<', ex)]
    tag_closes = [m.start() for m in re.finditer('>', ex)]
    word = ''
    furigana = ''
    hira = ''
    find_text = False

    for i in range(len(tag_starts)-1):
        current_text = [None, None, None, None]
        current_tag = ex[tag_starts[i]+1:tag_closes[i]]

        if example: # get the start and end indeces of grammar point characters in current example
            if 'text-primary-accent' in current_tag:
                find_text = True # look for next text to assign as a grammar character
            if '/span' in current_tag and find_text: # if the grammar character styling tag has finished, stop assigning text as grammar character
                find_text = False

        if current_tag == 'ruby': # upcoming word has furigana attached
            word = ex[tag_closes[i]+1:tag_starts[i+1]]
        elif current_tag == 'rt':
            furigana = ex[tag_closes[i]+1:tag_starts[i+1]]
            current_text[0] = word # append the kanji and furigana after furigana appears
            current_text[1] = furigana
            if find_text:
                current_text[3] = True

            word = '' # reset these for new kanji word and furigana
            furigana = ''
        else:
            # if en:
            #     if current_tag == 'strong':
            #         hira = ex[tag_closes[i]+1:tag_starts[i+1]]
            #         find_text = True
            if not current_tag == 'rp': # rp is a tag that is only used around parentheses so do not need it
                hira = ex[tag_closes[i]+1:tag_starts[i+1]] # regular hiragana text appears

                if not hira == '' and not hira == '\n': # all tags produce some text, even if it is empty, so filter it out
                    current_text[2] = hira
                    if find_text:
                        current_text[3] = True



        if not all(x is None for x in current_text):
            text.append(current_text) 
          
    return text

In [12]:
for url in tqdm(grammar_points_list):
    
    full_url = BASE_URL + url
    # full_url = "https://bunpro.jp/grammar_points/%E3%82%92"
    # full_url = "https://bunpro.jp/grammar_points/%E8%81%9E%E3%81%93%E3%81%88%E3%82%8B"
    page_data = requests.get(full_url)

    soup = BeautifulSoup(page_data.text, "html.parser")

    # TODO: FILL IN GRAMMAR POINT INFORMATION AND ADD TO grammar_data_df
    # USE THAT ID FOR examples_df ENTRIES

    level = soup.find("p", {"class": "text-primary-contrast md:text-primary-fg"})
    level = str(level.text)[1:2]

    grammar_point_jp = soup.find("span", {"class": "bp-ddw undefined"})
    grammar_point_jp = extract_text(str(grammar_point_jp))

    meaning_en = soup.find("span", {"class": "mt-4 block text-body text-primary-contrast md:text-subtitle md:text-primary-fg"})
    meaning_en = meaning_en.text

    description = soup.find("div", {"class": "bp-ddw bp-writeup-body prose"})
    description = extract_text(str(description))

    grammar_data = {"level": level, "grammar_point_jp": grammar_point_jp, "meaning_en": meaning_en, "description": description}

    grammar_data_df.loc[len(grammar_data_df)] = grammar_data

100%|██████████| 938/938 [03:57<00:00,  3.95it/s]

In [13]:
grammar_data_df['page_url'] = grammar_points_list

In [14]:
grammar_data_df.to_csv('grammar_points.csv', encoding='utf-16', header=False)

In [6]:
df = pd.read_csv('grammar_points.csv', encoding='utf-16', index_col=0, names=["level", "grammar_point_jp", "meaning_en", "description", "page_url"])

examples_df = pd.DataFrame(columns=["grammar_id", "text_jp", "text_en", "grammar_char_locations_jp", "grammar_char_locations_en"])

def get_grammar_char_locs(text: list):
    locs = []
    char_index = 0
    scan = False
    for i in range(len(text)):
        if text[i][3] is not None:
            if not scan:
                scan = True
                current_loc = []
                current_loc.append(char_index)
        else:
            if scan:
                scan = False
                current_loc.append(char_index)
                locs.append(current_loc)

        if text[i][0] is not None:
            char_index += len(text[i][0])
        else:
            char_index += len(text[i][2])
    if len(current_loc) == 1: # in case text ends with the grammar characters, add the end index manually
        current_loc.append(char_index)
        locs.append(current_loc)    
    
    return locs

In [ ]:
# TODO: Get english translation of example

# print(df)
for rec in tqdm(range(1)):
    url = BASE_URL + df.loc[rec]['page_url']
    url = 'https://bunpro.jp/grammar_points/%E3%81%A0'
    # grammar_id = df.index[rec]

    page_data = requests.get(url)

    soup = BeautifulSoup(page_data.text, "html.parser")
    
    examples = soup.find_all("p", {"class": "bp-ddw prose text-large md:text-subtitle"})
    num_examples = len(examples)

    examples_en = soup.find_all("p", {"class": "bp-sdw text-body"})
    print(examples_en)

    # for ex in range(num_examples):
    #     text_jp = extract_text(str(examples[ex]), example=True)
    #     grammar_char_locations_jp = get_grammar_char_locs(text_jp)

        # text_en = extract_text(str(examples_en[ex]), example=True, en=True)
        # print(examples_en[ex])
        # data = {"grammar_id": grammar_id, "text_jp": text_jp, "text_en": text_en, "grammar_char_locations_jp": grammar_char_locations_jp, "grammar_char_locations_en"}

    # for ex in soup.find_all("p", {"class": "bp-ddw prose text-large md:text-subtitle"}):
    #     text = extract_text(str(ex), example=True) 
    #     print(text)
    #     grammar_char_locations = get_grammar_char_locs(text)
    #     data = {"grammar_id": grammar_id, "text": text, "grammar_char_locations": grammar_char_locations}
    #     examples_df.loc[len(examples_df)] = data

  0%|          | 0/1 [00:21<?, ?it/s]

KeyboardInterrupt:

In [17]:
examples_df

,grammar_id,text,grammar_char_locations
0,0,"[[私, わたし, None, None], [None, None, だ, True], ...","[[1, 2]]"
1,0,"[[本, ほん, None, None], [None, None, だ, True], [...","[[1, 2]]"
2,0,"[[猫, ねこ, None, None], [None, None, だ, True], [...","[[1, 2]]"
3,0,"[[学生, がくせい, None, None], [None, None, だ, True]...","[[2, 3]]"
4,0,"[[綺麗, きれい, None, None], [None, None, だ, True],...","[[2, 3]]"
...,...,...,...
4684,937,"[[世, よ, None, None], [None, None, の, None], [流...","[[13, 19]]"
4685,937,"[[None, None, いかに, None], [世, よ, None, None], ...","[[26, 32]]"
4686,937,"[[花, はな, None, None], [None, None, の, None], [...","[[13, 17]]"
4687,937,"[[None, None, この, None], [花, はな, None, None], ...","[[6, 10]]"
4688,937,"[[道険, みちけわ, None, None], [None, None, しくとも、, N...","[[13, 19]]"

In [18]:
examples_df.to_csv('examples.csv', encoding='utf-16', header=False)

In [19]:
df_2 = pd.read_csv('examples.csv', encoding='utf-16', index_col=0 ,names=["grammar_id", "text", "grammar_char_locations"])

df_2

,grammar_id,text,grammar_char_locations
0,0,"[['私', 'わたし', None, None], [None, None, 'だ', T...","[[1, 2]]"
1,0,"[['本', 'ほん', None, None], [None, None, 'だ', Tr...","[[1, 2]]"
2,0,"[['猫', 'ねこ', None, None], [None, None, 'だ', Tr...","[[1, 2]]"
3,0,"[['学生', 'がくせい', None, None], [None, None, 'だ',...","[[2, 3]]"
4,0,"[['綺麗', 'きれい', None, None], [None, None, 'だ', ...","[[2, 3]]"
...,...,...,...
4684,937,"[['世', 'よ', None, None], [None, None, 'の', Non...","[[13, 19]]"
4685,937,"[[None, None, 'いかに', None], ['世', 'よ', None, N...","[[26, 32]]"
4686,937,"[['花', 'はな', None, None], [None, None, 'の', No...","[[13, 17]]"
4687,937,"[[None, None, 'この', None], ['花', 'はな', None, N...","[[6, 10]]"
4688,937,"[['道険', 'みちけわ', None, None], [None, None, 'しくと...","[[13, 19]]"

In [20]:
ex = df_2.loc[1210]

example = ''

ex_text = literal_eval(ex['text'])
print(ex_text)
for i in range(len(ex_text)):
    if ex_text[i][0] is not None:
        example += ex_text[i][0]
    else:
        example += ex_text[i][2]

example

[[None, None, 'スマホ', None], [None, None, 'を', None], ['使', 'つか', None, True], [None, None, 'わせてくれないか', True], [None, None, '？', None]]

'スマホを使わせてくれないか？'